on:
  push:
    branches: [ 'main' ]

jobs:
  build:
    name: Release Go Binary
    strategy:
      matrix:
        include:
          - platform: linux_amd64
            os: ubuntu-latest
            GOOS: linux
            GOARCH: amd64
          - platform: linux_arm64
            os: ubuntu-latest
            GOOS: linux
            GOARCH: arm64
          - platform: darwin_amd64
            os: macos-latest
            GOOS: darwin
            GOARCH: amd64
          - platform: darwin_arm64
            os: macos-latest
            GOOS: darwin
            GOARCH: arm64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go environment
        uses: actions/setup-go@v5.0.0
        with:
          go-version: '1.22'
      - name: Install dependencies
        if: matrix.GOOS == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-multilib gcc-aarch64-linux-gnu
      - name: Build binary
        run: |
          export CGO_ENABLED=1
          export GOOS=${{ matrix.GOOS }}
          export GOARCH=${{ matrix.GOARCH }}
          if [ "${{ matrix.GOARCH }}" = "arm64" &&  "${{ matrix.GOOS }}" = "linux" ]; then
            export CC=aarch64-linux-gnu-gcc
          fi
          bash build.sh -o OpenNG-${{ matrix.platform }}
