on:
  push:
    branches: [ 'main' ]

jobs:
  build:
    name: Release Go Binary
    strategy:
      matrix:
        include:
          - platform: linux_amd64
            os: ubuntu-latest
          - platform: linux_arm64
            os: ubuntu-latest
          - platform: darwin_amd64
            os: macos-latest
          - platform: darwin_arm64
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go environment
        uses: actions/setup-go@v5.0.0
        with:
          go-version: '1.22'
      - name: Install dependencies
        if: matrix.platform.split('_')[0] == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-multilib
      - name: Build binary
        run: |
          export CGO_ENABLED=1
          export GOOS=${{ matrix.platform.split('_')[0] }}
          export GOARCH=${{ matrix.platform.split('_')[1] }}
          bash build.sh -o OpenNG-${{ matrix.platform }}
